@ECHAddress = http://localhost:5202

### Create product
POST {{ECHAddress}}/api/products
Content-Type: application/json

{
  "name": "eho",
  "description": "Fresh Tomato ready for eating",
  "price": 80.5,
  "StockQuantity": 100
}


### Get all products without cache
GET {{ECHAddress}}/api/products

### Get all products (test caching)
GET {{ECHAddress}}/api/products/products-with-cache
Accept: application/json
